using System;
using Cysharp.Threading.Tasks;

namespace HelloDev.Saving.Interfaces
{
    /// <summary>
    /// Represents any object that participates in the save system.
    /// 
    /// Savables can represent global systems, scene objects,
    /// or dynamically spawned runtime objects.
    /// </summary>
    public interface ISavable
    {
        /// <summary>
        /// Stable unique identifier used to identify this object in save data.
        /// Must never change after creation.
        /// </summary>
        string SaveId { get; }

        /// <summary>
        /// Type of the snapshot object produced by this savable.
        /// </summary>
        Type StateType { get; }

        /// <summary>
        /// Captures the current state of this object.
        /// </summary>
        /// <returns>
        /// A serializable snapshot object.
        /// </returns>
        object SaveState();

        /// <summary>
        /// Restores this object from previously saved state.
        /// </summary>
        /// <param name="state">
        /// Snapshot object generated by <see cref="SaveState"/>.
        /// </param>
        UniTask LoadState(object state);
    }
}